[package]
name = "bool_expr_parser"
version = "0.3.9"
edition = "2021"
readme = "README.md"
repository = "https://github.com/dzhibas/bool_expr_parser"
authors = ["Nikolajus Krauklis <nikolajus@gmail.com>"]

[dependencies]
pest = "*"
pest_derive = "*"